services:
  - type: web
    name: solo-leveling-fitness
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        sync: false
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-store